services:
  gin-bili-pic:
    container_name: gin-bili-pic
    image: linweiyuan/gin-bili-pic
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - TZ=Asia/Shanghai
    restart: unless-stopped
